# Generated by Django 2.2.16 on 2022-06-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220617_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.TextField(blank=True, verbose_name='Код подтверждения'),
        ),
    ]
