# Generated by Django 2.2.16 on 2022-06-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220617_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': ('Категория',), 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': ('Комментарий',), 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': ('Жанр',), 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='genretitle',
            options={'verbose_name': ('Связь произведения и жанра',), 'verbose_name_plural': 'Связи произведений и жанров'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': ('Отзыв',), 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': ('Произведение',), 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': ('Пользователь',), 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.FloatField(default=None, null=True, verbose_name='Рейтинг произведения'),
        ),
    ]
